Member 도메인 클래스 수정
f-lab-edu/study-together pull request #42
Opened 2023-12-05 14:14 UTC by wooni97

2023-12-12 01:13 UTC, f-lab-inno requested changes

2023-12-12 01:13 UTC, f-lab-inno commented on src/main/java/dev/flab/studytogether/domain/member/repository/MemberRepositoryImpl.java
> +        return Member.createWithSequenceId((Integer) key, member.getId(), member.getPassword(), member.getNickname());
기존 intValue() 메소드 호출에서 형변환으로 변경하신 이유가 무엇일까요? `executeAndReturnKey`의 반환될 타입이 int 하위호환 타입인것임이 확실한 경우인것처럼 보이는데, Integer 타입으로 선언해도 되지 않을까요?

2023-12-12 01:13 UTC, f-lab-inno commented on src/main/java/dev/flab/studytogether/domain/member/entity/Member.java
> +    private Member(int sequenceId, String id, String password, String nickname){
변수명이 조금 더 길어지더라도, 명시적인 표현 방법 아주 좋습니다! 👍

2023-12-12 01:13 UTC, f-lab-inno commented on src/main/java/dev/flab/studytogether/domain/member/entity/Member.java
>      }
객체 생성에 따른 생성자 이름 부여 차원의 정적 팩토리 메소드 패턴 사용 사례도 좋네요.

2023-12-13 07:49 UTC, wooni97 commented on src/main/java/dev/flab/studytogether/domain/member/repository/MemberRepositoryImpl.java
> +        return Member.createWithSequenceId((Integer) key, member.getId(), member.getPassword(), member.getNickname());
이 부분은 제가 잘못 수정한 부분이네요! 다시 intValue() 메소드 호출로 변경했습니다.

2023-12-19 01:06 UTC, merged