[#42] 공통 API 응답 객체 생성
f-lab-edu/study-together pull request #43
Opened 2023-12-05 15:53 UTC by wooni97

2023-12-12 01:12 UTC, thxwelchs requested changes

2023-12-12 01:12 UTC, thxwelchs commented on src/main/java/dev/flab/studytogether/domain/member/controller/MemberAPIController.java
> +@RequestMapping("/api/members")
/api prefix를 붙인 이유가 무엇일까요?

2023-12-12 01:12 UTC, thxwelchs commented on src/main/java/dev/flab/studytogether/domain/member/controller/MemberAPIController.java
> +        return SingleApiResponse.ok(response);
기존 구조에서는 login 페이지로 리다이렉트 하는 view 역할이었는데, 이 부분이 API 구조로 변경되는것을 의도하신걸까요?

2023-12-12 01:12 UTC, thxwelchs commented on src/main/java/dev/flab/studytogether/domain/member/dto/MemberResponse.java
> +@Data
@Data 어노테이션은 어떤 역할을 하는것일까요? 이것을 사용함으로써 불필요한 어노테이션이 같이 사용되고 있진 않을까요?

2023-12-12 01:12 UTC, thxwelchs commented on src/main/java/dev/flab/studytogether/response/ListApiResponse.java
> +public class ListApiResponse<T> extends CommonResponse {
SingleApiResponse와 비교해보았을 때, message 필드 보유 여부 외에는 큰 차이가 없어보이는데, List, Single 구조로 분리해놓으신 이유가 있으실까요?

2023-12-12 01:12 UTC, thxwelchs commented on src/main/java/dev/flab/studytogether/response/CommonResponse.java
> +public class CommonResponse {
공통 응답 객체를 일일이 모든 컨트롤러 메소드에 코딩하지 않고도, 공통적으로 적용할 수 있는 방법이 있을까요? 스프링에서는 이러한 핵심관심사와 공통적인 부가 관심사를 나누는 개념을 상당히 선호하고 있습니다. (AOP) 직접 구현하는 방법과, ControllerAdvice, RestControllerAdvice에 대해 학습해보세요!

2023-12-12 01:40 UTC, f-lab-inno requested changes

2023-12-12 01:40 UTC, f-lab-inno commented on src/main/java/dev/flab/studytogether/domain/member/controller/MemberAPIController.java
> +@RequestMapping("/api/members")
/api prefix를 붙인 이유가 무엇일까요?

2023-12-12 01:40 UTC, f-lab-inno commented on src/main/java/dev/flab/studytogether/domain/member/controller/MemberAPIController.java
> +        return SingleApiResponse.ok(response);
기존 구조에서 redirect를 하는 부분도 변경되었는데 이것도 의도된 변경일까요?

2023-12-12 01:40 UTC, f-lab-inno commented on src/main/java/dev/flab/studytogether/domain/member/dto/MemberResponse.java
> +@Data
@Data 어노테이션은 어떤 역할을 하는것일까요? 이것을 사용함으로써 불필요한 어노테이션이 같이 사용되고 있진 않을까요?

2023-12-12 01:40 UTC, f-lab-inno commented on src/main/java/dev/flab/studytogether/response/CommonResponse.java
> +public class CommonResponse {
공통 응답 객체를 일일이 모든 컨트롤러 메소드에 코딩하지 않고도, 공통적으로 적용할 수 있는 방법이 있을까요? 스프링에서는 이러한 핵심관심사와 공통적인 부가 관심사를 나누는 개념을 상당히 선호하고 있습니다. (AOP) 직접 구현하는 방법과, ControllerAdvice, RestControllerAdvice에 대해 학습해보세요!

2023-12-12 01:40 UTC, f-lab-inno commented on src/main/java/dev/flab/studytogether/response/ListApiResponse.java
> +public class ListApiResponse<T> extends CommonResponse {
SingleApiResponse와 비교해보았을 때, message 필드 보유 여부 외에는 큰 차이가 없어보이는데, List, Single 구조로 분리해놓으신 이유가 있으실까요?

2023-12-13 08:02 UTC, wooni97 commented on src/main/java/dev/flab/studytogether/domain/member/controller/MemberAPIController.java
> +@RequestMapping("/api/members")
API 엔드포인트와 다른 엔드포인트를 분리해서 일관성 있게 관리하려고 붙였습니다

2023-12-13 14:02 UTC, wooni97 commented on src/main/java/dev/flab/studytogether/domain/member/dto/MemberResponse.java
> +@Data
@toString + @getter + @setter + @RequiredArgsConstructor + @EqualsAndHashCode
위의 어노테이션을 한꺼번에 설정해주는 어노테이션인데, dto라서 추후에 해당 어노테이션들이 필요할것이라 생각했지만
지금으로 봤을땐 불필요한 어노테이션들이 더 많은게 맞습니다. 필요한 어노테이션만 사용하도록 수정할게요!

2023-12-13 15:12 UTC, wooni97 commented on src/main/java/dev/flab/studytogether/response/ListApiResponse.java
> +public class ListApiResponse<T> extends CommonResponse {
컨트롤러에서 메서드를 보고 해당 API가 단일 객체를 다루는지, 여러 객체를 다루는지 명확하게 전달하고 싶어서 분리한게 가장 큰 이유입니다.

2023-12-15 16:59 UTC, wooni97 commented on src/main/java/dev/flab/studytogether/domain/member/controller/MemberAPIController.java
> +        return SingleApiResponse.ok(response);
네 그렇습니다. 우선은 api 설계와 구현에  집중하고 싶어 변경했습니다. 추후에 프론트단이 만들어지면 다시 생각해보려고요!

2023-12-15 17:03 UTC, wooni97 commented on src/main/java/dev/flab/studytogether/response/CommonResponse.java
> +public class CommonResponse {
컨트롤러 메소드에 공통 응답 객체가 명시돼있는게 코드를 보는 입장에서 편하다고 생각하여 그렇게 구현했는데
고민을 해보니 반복적인 작업이 맞고, 혹여나 나중에 응답 객체와 관련하여 변경이 일어난다면 api 갯수만큼 변경해야하는 경우가 생길것 같아 공통 부가 관심사로 분리하는게 맞다고 생각이 드네요! 이 부분은 수정하고 새롭게 pr 올리겠습니다.

2023-12-15 17:07 UTC, wooni97 commented on src/main/java/dev/flab/studytogether/response/ListApiResponse.java
> +public class ListApiResponse<T> extends CommonResponse {
어차피 제네릭을 사용하고 있고, 저번에 말씀 주신대로 응답 data에 List 외에도 다른 자료구조가 들어갈 수 있는 확장성을 고려하여 List, Single로 분리하는게 불필요해보여서 수정했습니다!

2023-12-19 01:08 UTC, f-lab-inno commented on src/main/java/dev/flab/studytogether/domain/member/dto/MemberResponse.java
> +@Data
좋습니다. @Data 어노테이션이 포함하고 있는 어노테이션들의 사용 목적을 명확하게 인지하고 사용해주시면 좋습니다!

2023-12-19 01:08 UTC, merged