[#33] 아이디 중복 확인 로직 구현
f-lab-edu/study-together pull request #44
Opened 2023-12-05 16:11 UTC by wooni97

#33

2023-12-12 01:19 UTC, thxwelchs requested changes

2023-12-12 01:40 UTC, f-lab-inno requested changes

2023-12-12 01:40 UTC, f-lab-inno commented on src/main/java/dev/flab/studytogether/domain/member/repository/MemberRepositoryImpl.java
> +                "SELECT EXISTS (SELECT 1 FROM MEMBER WHERE id = ?)", Boolean.class, id));
Boolean.TRUE.equals 연산 후 반환하는 이유가 무엇일까요?

2023-12-15 16:57 UTC, wooni97 commented on src/main/java/dev/flab/studytogether/domain/member/repository/MemberRepositoryImpl.java
> +                "SELECT EXISTS (SELECT 1 FROM MEMBER WHERE id = ?)", Boolean.class, id));
id가 존재하는지 확인하고 존재하면 true로 반환해주기 위해서입니다!

2023-12-19 01:13 UTC, f-lab-inno commented on src/main/java/dev/flab/studytogether/domain/member/repository/MemberRepositoryImpl.java
> +                "SELECT EXISTS (SELECT 1 FROM MEMBER WHERE id = ?)", Boolean.class, id));
NPE 방어의 수단이 아닌 경우라면, 이미 Boolean 타입으로 반환될것으로 예상되어 말씀드려보았습니다!

2023-12-19 04:28 UTC, wooni97 commented on src/main/java/dev/flab/studytogether/domain/member/repository/MemberRepositoryImpl.java
> +                "SELECT EXISTS (SELECT 1 FROM MEMBER WHERE id = ?)", Boolean.class, id));
아 그렇네요! Boolean.TRUE.equals 연산은 불필요하네요. 이것도 수정하겠습니다

2023-12-19 05:13 UTC, wooni97 commented on src/main/java/dev/flab/studytogether/domain/member/repository/MemberRepositoryImpl.java
> +                "SELECT EXISTS (SELECT 1 FROM MEMBER WHERE id = ?)", Boolean.class, id));
연산 없이도 Boolean 타입으로 반환되는게 맞아서 수정했습니다!

2023-12-19 05:13 UTC, merged