[#34]권한 관리 서비스 구현
f-lab-edu/study-together pull request #45
Opened 2023-12-06 14:16 UTC by wooni97

#34

2023-12-12 01:21 UTC, thxwelchs requested changes

2023-12-12 01:21 UTC, thxwelchs commented on src/main/java/dev/flab/studytogether/domain/member/service/AuthService.java
> +    private HttpSession httpSession;
도메인 패키지 내에 servlet 스펙인 HttpSession 클래스 의존이 생기는것에 대한 부분은 고민해보셨을까요?

2023-12-12 01:39 UTC, f-lab-inno requested changes

2023-12-12 01:39 UTC, f-lab-inno commented on src/main/java/dev/flab/studytogether/domain/member/service/AuthService.java
> +    private HttpSession httpSession;
도메인 패키지 내에 servlet 스펙인 HttpSession 클래스 의존이 생기는것에 대한 부분은 고민해보셨을까요?

2023-12-15 17:10 UTC, wooni97 commented on src/main/java/dev/flab/studytogether/domain/member/service/AuthService.java
> +    private HttpSession httpSession;
세션에 권한을 부여하고 있기에 권한 관리 서비스에서는 서비스 레이어가 HttpSession을 불가피하게 의존할 수 밖에 없다고 생각을 했는데, 이 부분 관련해서는 지난번에 조언 주신 내용에 대해서 더 고민해보고 변경할 수 있다면 변경해볼게요

2023-12-19 01:13 UTC, merged