[#37]StudyRoom 조회 기능 구현
f-lab-edu/study-together pull request #48
Opened 2023-12-07 15:07 UTC by wooni97

#37 
- 활성화된 전체 스터디룸 조회
- 현재 입장 가능한 스터디룸 조회

2023-12-12 01:26 UTC, thxwelchs commented on src/main/java/dev/flab/studytogether/domain/room/controller/StudyRoomApiController.java
> +    private StudyRoomResponse convertToStudyRoomResponse(StudyRoom studyRoom) {
요건 StudyRoomResponse 내부에 convert 역할을 주어도 좋을것 같아요..

2023-12-12 01:28 UTC, thxwelchs requested changes

2023-12-12 01:28 UTC, thxwelchs commented on src/main/java/dev/flab/studytogether/domain/room/controller/StudyRoomApiController.java
> +    private StudyRoomResponse convertToStudyRoomResponse(StudyRoom studyRoom) {
요건 StudyRoomResponse 내부에 역할을 주어도 좋을것 같아요.

2023-12-12 01:41 UTC, f-lab-inno requested changes

2023-12-12 01:41 UTC, f-lab-inno commented on src/main/java/dev/flab/studytogether/domain/room/controller/StudyRoomApiController.java
> +    }
요건 StudyRoomResponse 내부에 역할을 주어도 좋을것 같아요.

2023-12-15 16:56 UTC, wooni97 commented on src/main/java/dev/flab/studytogether/domain/room/controller/StudyRoomApiController.java
> +    }
넵 수정했습니다

2023-12-19 02:37 UTC, merged